### ISSUE TITLE
Nested fields

### ISSUE THREAD

**Issue by j** [mscdex/reformed#1]
I don't see any examples on how to nest fields.

How can I have the following?

name = user[first]
addresses = address[0][street], address[1][street]

And so on so forth.  Is this supported here?

**Comment by mscdex** [comment]
Multiple values are allowed (for fields with the same name), but there is no other special handling/behavior for field names currently.

**Comment by j** [comment]
Okay, and sorry for not digging into code first.  I'm currently trying to build a wrapper on top of this for "pretty form printing" and being able to pass a form instance to a view for rendering, so I haven't gotten into nested fields.

Is this feature lacking in reformed or busboy?  I can tinker with it later, so thought I'd ask first before exploring since my focus is on another library.

**Comment by mscdex** [comment]
Busboy emits events for every field/file as-is, so it's up to any module (e.g. reformed) that builds on top of that to do what whatever with those fields/files.

**Comment by j** [comment]
Okay, thanks!  I'll look into it eventually :)
